---
network:
  vpc: 192.168.0.0/16
  public_subnets:
    - 192.168.1.0/24
    - 192.168.2.0/24
    - 192.168.3.0/24
  private_subnets:
    - 192.168.10.0/24
    - 192.168.20.0/24
    - 192.168.30.0/24
